### ISSUE TITLE
Install libssl1.0-dev instead of libssl-dev with apt

### ISSUE THREAD

**Issue by mvz** [postmodern/ruby-install#287]
On recent versions of Debian, libssl-dev installs dev files for libssl 1.1. CRuby fails to build with that, and needs libssl 1.0 instead.

Please consider installing libssl1.0-dev instead.

**Comment by Shelvak** [comment]
Same issue in archlinux.
I tried to install openssl-1.0 and lib32-openssl-1.0 to get the lib working, and put `--with-openssl-dir` but i didn't work.
I tried with env var and with the option param
`RUBY_CONFIGURE_OPTS=--with-openssl-dir=path/openssl/ ruby-install ruby 2.1.9 -- --with-openssl-dir=path/openssl/
`
Always get the same error
```
/usr/include/openssl/asn1_mac.h:10:2: error: #error "This file is obsolete; please update your software."               
 #error "This file is obsolete; please update your software."
```

**Comment by guilhermefeitosa66** [comment]
Same issue in Elementary OS 0.4.1 Loki amd64.
INPUT: $ rvm install 2.3.3
OUTPUT:
Warning, new version of rvm available '1.29.2', you are using older version '1.29.1'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Searching for binary rubies, this might take some time.
No binary rubies available for: debian/9/x86_64/ruby-2.3.3.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for debian.
Installing requirements for debian.
Updating systemguilherme password required for 'apt-get --quiet --yes update': ..          
..
Installing required packages: **libssl1.0-dev**....
Error running 'requirements_debian_libs_install libssl1.0-dev',
showing last 15 lines of /home/guilherme/.rvm/log/1498394767_ruby-2.3.3/package_install_libssl1.0-dev.log
++ [[ -d /usr/local/sbin ]]
++ [[ :/home/guilherme/.rvm/gems/ruby-2.4.0@rails-4.2/bin:/home/guilherme/.rvm/gems/ruby-2.4.0@global/bin:/home/guilherme/.rvm/rubies/ruby-2.4.0/bin:/home/guilherme/.dropbox-bin:/home/guilherme/bin:/home/guilherme/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/guilherme/.rvm/bin:/home/guilherme/.rvm/bin: != *\:\/\u\s\r\/\l\o\c\a\l\/\s\b\i\n\:* ]]
++ [[ -n '' ]]
++ command_to_run=(__rvm_sudo -p "%p password required for '$*': " "${command_to_run[@]}")
++ __rvm_sudo -p '%p password required for '\''apt-get --no-install-recommends --yes install libssl1.0-dev'\'': ' apt-get --no-install-recommends --yes install libssl1.0-dev
++ command sudo -p '%p password required for '\''apt-get --no-install-recommends --yes install libssl1.0-dev'\'': ' apt-get --no-install-recommends --yes install libssl1.0-dev
++ sudo -p '%p password required for '\''apt-get --no-install-recommends --yes install libssl1.0-dev'\'': ' apt-get --no-install-recommends --yes install libssl1.0-dev
Lendo listas de pacotes...
Construindo árvore de dependências...
Lendo informação de estado...
E: Impossível encontrar o pacote libssl1.0-dev
E: Couldn't find any package by glob 'libssl1.0-dev'
E: Não foi possível encontrar o pacote através da expressão regular 'libssl1.0-dev'
++ return 100
++ return 100
Requirements installation failed with status: 100.

**Comment by bugthing** [comment]
This is/was an issue for me using debian stretch (v9) .. I got around the issue by installing all dependencies manually (something like: `apt install libyaml-dev  libxml2-dev libssl1.0-dev libreadline-dev zlib1g zlib1g-dev libbison-dev libxslt1-dev libxml2-dev`) before running the ruby install telling it to NOT install dependencies, like so `ruby-install ruby --no-install-deps  2.3.4`

**Comment by crivotz** [comment]
Problem seem related to the ruby version (2.1 2.2 2.3)

**Comment by go2null** [comment]
`ruby_build`:
- https://github.com/rbenv/ruby-build/issues/1006
- https://github.com/rbenv/ruby-build/issues/1111
- https://github.com/rbenv/ruby-build/wiki#openssl-usrincludeopensslasn1_mach102-error-error-this-file-is-obsolete-please-update-your-software

`rvm`:
- https://github.com/rvm/rvm/issues/3862


Just encountered this today, again, (using `ruby-install`).

**Comment by Shelvak** [comment]
If anyone needs a "quick fix" for any SO, installing `openssl-1.0` from official repos or manually, then you can do: `PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig ruby-install ruby 2.X.X`

Obviously `PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig`  with the correct path for openssl-1.0 pkgconfig.

Cheers.

**Comment by kolosek** [comment]
In order to fix rvm get master, you can use this command:
echo insecure >> ~/.curlrc
And then run the rvm get master. It worked for me 18.04.1 Ubuntu

**Comment by mvz** [comment]
@kolosek that is a good tip for rvm users, but I don't see how this has anything to do with this ticket, which is about installing older versions of Ruby with ruby-install?

**Comment by jleo3** [comment]
@dgtized comment was a live-saver! Thank you!

**Comment by jonleighton** [comment]
I've had this problem trying to install Ruby 2.1.5 on Fedora 30, where openssl 1.0 is not available to install from the package manager at all. I was able to solve it by manually downloading and building openssl and then linking Ruby against this custom version. Here are the steps:

``` bash
$ cd ~/src
$ wget https://www.openssl.org/source/openssl-1.0.2s.tar.gz
$ tar xvzf openssl-1.0.2s.tar.gz
$ cd openssl-1.0.2s
$ mkdir ~/.rubies/openssl-1.0.2s
$ ./config --prefix=$HOME/.rubies/openssl-1.0.2s --shared
$ make
$ make install
$ ruby-install ruby-2.1.5 -- --with-openssl-dir=$HOME/.rubies/openssl-1.0.2s
```

**Comment by jonleighton** [comment]
I also needed to link my custom-install OpenSSL config with my system OpenSSL config, as certification verification was failing with the default config:

``` bash
rm -r ~/.rubies/openssl-1.0.2s/ssl
ln -s /etc/pki/tls ~/.rubies/openssl-1.0.2s/ssl
```

The `/etc/pki/tls` location may well be different on other distros.

**Comment by Madh93** [comment]
@Shelvak solution works like a charm.

In my case to install Ruby 2.3.8 on Manjaro (Arch-based) it's necessary to do:

    sudo pacman -S openssl-1.0
    PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig ruby-install ruby 2.3.8

**Comment by eregon** [comment]
FWIW, this is expected, Ruby <= 2.3 (all out-of-life BTW) do not support OpenSSL > 1.1.

As long as `ruby-install` does not support per-version dependencies I think this cannot be solved unfortunately.

**Comment by amboxer21** [comment]
I have tried a bunch of different work arounds centered around PKG_CONFIG_PATH but none worked. I ended up adding older sources to my source.list and installed the necessary version of openssl. Then I was able to install ruby-2.3.3 without an issue.

> Source file location:
```
/etc/apt/sources.list
```

>Debian sources that i appended to my source file:
```
deb http://ftp.us.debian.org/debian/ stretch main contrib non-free
deb http://ftp.us.debian.org/debian/ stretch-updates main contrib non-free
deb http://security.debian.org/debian-security/ stretch/updates main contrib non-free
```

You have to update after:
```
sudo apt update
```
> Install necessary version of openssl
```
sudo apt install libssl1.0-dev
```

> Installation output:
```
anthony@ghost:~/Documents/Source/ruby-2.3.3$ sudo apt-get install libssl1.0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libssl1.0.2
The following packages will be REMOVED:
  libcurl4-openssl-dev
The following NEW packages will be installed:
  libssl1.0-dev libssl1.0.2
0 upgraded, 2 newly installed, 1 to remove and 0 not upgraded.
Need to get 2,877 kB of archives.
After this operation, 9,623 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://security.debian.org/debian-security stretch/updates/main amd64 libssl1.0.2 amd64 1.0.2u-1~deb9u1 [1,304 kB]
Get:2 http://security.debian.org/debian-security stretch/updates/main amd64 libssl1.0-dev amd64 1.0.2u-1~deb9u1 [1,573 kB]
Fetched 2,877 kB in 0s (9,690 kB/s)  
Preconfiguring packages ...
(Reading database ... 301451 files and directories currently installed.)
Removing libcurl4-openssl-dev:amd64 (7.64.0-4) ...
Selecting previously unselected package libssl1.0.2:amd64.
(Reading database ... 301429 files and directories currently installed.)
Preparing to unpack .../libssl1.0.2_1.0.2u-1~deb9u1_amd64.deb ...
Unpacking libssl1.0.2:amd64 (1.0.2u-1~deb9u1) ...
Selecting previously unselected package libssl1.0-dev:amd64.
Preparing to unpack .../libssl1.0-dev_1.0.2u-1~deb9u1_amd64.deb ...
Unpacking libssl1.0-dev:amd64 (1.0.2u-1~deb9u1) ...
Setting up libssl1.0.2:amd64 (1.0.2u-1~deb9u1) ...
Setting up libssl1.0-dev:amd64 (1.0.2u-1~deb9u1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10) ...
anthony@ghost:~/Documents/Source/ruby-2.3.3$
```

**Comment by mvz** [comment]
@amboxer21 to give passers-by a complete picture, can you add your full `ruby-install` invocation?

**Comment by amboxer21** [comment]
Sorry @mvz but I do not use RVM but I will show my gem env

```
anthony@ghost:~/Documents/Rails/hosted/hpbxgui$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/ruby-2.3.3/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /home/anthony/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/local/ruby-2.3.3/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/ruby-2.3.3/bin
  - SPEC CACHE DIRECTORY: /home/anthony/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/ruby-2.3.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/ruby-2.3.3/lib/ruby/gems/2.3.0
     - /home/anthony/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/ruby-2.3.3/bin
     - /usr/sbin
     - /sbin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/local/games
     - /usr/games
anthony@ghost:~/Documents/Rails/hosted/hpbxgui$
```

**Comment by mvz** [comment]
@amboxer21 I didn't mention RVM. I'm talking about ruby-install.

**Comment by amboxer21** [comment]
Sorry, I thought ruby-install was an RVM thing. I manually install ruby from source, i.e. configure, make, and make install. That ruby-install command is not installed on my system.

**Comment by mvz** [comment]
@amboxer21 This is the issue tracker for `ruby-install` :rofl:

**Comment by mvz** [comment]
Closing this since it won't be fixed, I don't need it anymore, and there's too much noise.

**Comment by amboxer21** [comment]
What a rude person you are! We both had the same issue with openssl causing our attempted installs to not install properly. whether it be through ruby-install or manual installation. Openssl seems to be the culprit. Do you honestly believe that out of all the devs in the world, that there won't be someone like me to come along in search of answers? Someone like me who has the same issue? I am just deversifying the solution to accommodate others who have the openssl issue but who aren't using ruby-install. I think you need to broaden your knowledge, skills, and your ability to be a good human being. I am going to delete these comments at the end of the day. I am leaving this for you to read. I am not going to be made a fool for trying to help others. Thanks.

**Comment by mvz** [comment]
@amboxer21 maybe you can open a stackoverflow issue that is more suited for general tips. I'm just cleaning up ruby-install's issue tracker and my github notifications. Sorry if you thought that was rude.

**Comment by rarkins** [comment]
In case it helps anyone, this worked for me to build Ruby 2.3.x into an Ubuntu 18.04-based Dockerfile:

```Dockerfile
RUN echo "deb http://security.ubuntu.com/ubuntu bionic-security main" >> /etc/apt/sources.list

RUN apt-cache policy libssl1.0-dev && \
  apt-get update && \
  apt-get install -y libssl1.0-dev && \
  apt-cache policy libssl1.0-dev && \
  apt-get install -y --no-install-recommends git curl build-essential make gcc zlib1g-dev libssl1.0-dev

RUN cd /tmp && \
  curl -L https://github.com/postmodern/ruby-install/archive/v0.7.0.tar.gz > ruby-install-0.7.0.tar.gz && \
  tar -xzvf ruby-install-0.7.0.tar.gz && \
  cd ruby-install-0.7.0/ && \
  make install && \
  cd /tmp && \
  rm -rf ruby*

ARG RUBY_VERSION

RUN ruby-install -c -j4 --system "ruby-${RUBY_VERSION}" --no-install-deps -- --disable-install-doc --with-openssl-dir="/usr/lib/x86_64-linux-gnu/pkgconfig/"
```

There may be a few pieces that could be trimmed but it took hours or trial and error to get one to work so I'm just leaving it as-is.

**Comment by roshin-torqata** [comment]
If you're on Debian 11 (bullseye), and unable to install `libssl1.0-dev` then do the following:

Add the following two sources
```shell
echo "deb http://deb.debian.org/debian/ stretch main contrib non-free" >> /etc/apt/sources.list.d/source.list 
echo "deb-src http://deb.debian.org/debian stretch main contrib non-free" >> /etc/apt/sources.list.d/source.list
```

Then run `apt-get update`

and finally `apt install libssl1.0-dev`

Here's the [Source](https://github.com/rvm/rvm/issues/4764#issuecomment-527723675) for more info.

https://stackoverflow.com/a/73188929/7345709
