### ISSUE TITLE
`ruby-install rubinius 2.0.0-rc1` doesn't work with Ruby 2.0.0

### ISSUE THREAD

**Issue by judofyr** [postmodern/ruby-install#51]
If you attempt to install rubinius 2.0.0-rc1 with Ruby 2.0.0 as active Ruby, you'll get a weird error:

```
undefined method `name' for -2.0000000000407714:Float
```

Even though this is Rubinius-bug, it would be nice if ruby-install would warn that you need Ruby 1.9.3.
